### ISSUE TITLE
Actualizar el recordatorio de clases

### ISSUE THREAD

**Issue by IAvecilla** [ilitteri/algo3-discord-bot#31]
Actualmente el aviso del bot de discord para cada clase incluye el link al zoom, deberiamos ver si la clase va a ser presencial para no mandarlo y no confundir mucho con ese tema.

**Comment by julitaras** [comment]
Y si es posible, en que aula tambien!

**Comment by ilitteri** [comment]
El template del mensaje para las clases virtuales está (se recicla el del cuatrimestre pasado).

Necesitaría ayuda para armar el template del mensaje para las clases presenciales

**Comment by ilitteri** [comment]
TODOs:

- [x] Identificar qué tipo de clase es la correspondiente al siguiente evento.
- [x] En base al tipo de clase enviar el template adecuado.
- [x] Hacer el template para las clases presenciales
- [x] Actualizar el link al zoom en el template del recordatorio de las clases virutales. (EDIT: es el mismo)
