### ISSUE TITLE
Parametrizar datos del cron para los avisos previo a las clases

### ISSUE THREAD

**Issue by ilitteri** [ilitteri/algo3-discord-bot#36]
Actualmente se tienen que modificar a mano cuatrimestre a cuatrimestre. El código está en `Client.ts`. 

- Una forma seria que chequee todo el tiempo en que parte del año estamos. 
- Otra sería tener una variable de entorno (que deberíamos modificar cuatrimestre a cuatrimestre en heroku). 

Se aceptan otras propuestas.

**Comment by josuebouchard** [comment]
Me gusta mas la segunda opcion. Es un trabajo que solo hay que hacer una vez por cuatrimestre (ya hay que verificar las variables de entorno una vez por cuatrimestre de todas maneras), y que permite que si fuera necesario, podriamos cambiarlo a mitad de cuatrimestre sin tener que hacer otro PR. Ademas es mas simple de implementar.

**Comment by ilitteri** [comment]
> Me gusta mas la segunda opcion. Es un trabajo que solo hay que hacer una vez por cuatrimestre (ya hay que verificar las variables de entorno una vez por cuatrimestre de todas maneras), y que permite que si fuera necesario, podriamos cambiarlo a mitad de cuatrimestre sin tener que hacer otro PR. Ademas es mas simple de implementar.

Tal cual! Esto que comentás me hizo pensar en que estaría bueno dejar escrito qué variables de entorno cambian cada cuatrimestre, por qué, y cómo hacerlo (para esta última agregar la limitación de heroku en la cantidad de usuarios que pueden modificar el proyecto)

**Comment by josuebouchard** [comment]
Solo para que quede registro, lo del tratamiento de las variables de entorno, actualizacion y documentacion se va a tratar en #37. 
Este issue solo queda para lo relativo a la parametrizacion de los cron jobs.

**Comment by ilitteri** [comment]
@IAvecilla pensó que sería mejor dejar todos los meses en dónde se van a dictar clases, lo cuál tiene todo el sentido del mundo. Se va a abrir un issue escífico para eso, dejando a este sin sentido.
