### ISSUE TITLE
[Feature] Agregar un recordatorio a las 17hs del mismo día de la cursada

### ISSUE THREAD

**Issue by ilitteri** [ilitteri/algo3-discord-bot#47]
## 🚀 Feature

Se quiere agregar un recordatorio a la tarde

## Motivación

A pedido de estudiantes, en sus palabras: "El de una hora antes sirve para recordar el aula, pero serviría más uno a la tarde para recordar las tareas a hacer" (más o menos).

## Implementación

Hay que agregar otro cron imitando la implementación de los existentes, pero con el horario de las 17hs

**Comment by julitaras** [comment]
Sinceramente pienso que es medio molesto tener dos recordarlos seguidos. Sobre todo porque es con 1 hs de diferencia en común y no hay uno que aporte mas que el otro. Optaría por dejar uno de los 2, ejemplo el de las 17 ya que da mas margen de error.

![image](https://user-images.githubusercontent.com/30576222/162328523-99d4707e-4aa1-4f5e-9017-8bddf1376c36.jpeg)

@ilitteri @IAvecilla :)

**Comment by julitaras** [comment]
Quizas se puede poner otro reminder, tipo: Recuerden leer esto!

**Comment by IAvecilla** [comment]
Coincido, creo que esto se habia hablado directamente con los estudiantes y me puede corregir @ilitteri pero es medio raro el doble recordatorio asi que podemos cambiarlo

**Comment by ilitteri** [comment]
Propuesta:

*Clases Presenciales*

- Un recordatorio tipo 16 con la información de las tareas para esa clase. 
- Otro recordatorio tipo 18/18:30 con los datos del aula y los temas que se van a ver en esa clase. 

*Clases Virtuales*

- Un recordatorio tipo 16 con la información de las tareas para esa clase. 
- Otro recordatorio tipo 18:50 con los datos del zoom.
